src/tasksandboards/boards/urls.py
from django.urls import path

from boards.views import BoardContentView, BoardsList, CreateBoard, CreateKanban


app_name = 'boards'

urlpatterns = [
    path('', BoardsList.as_view(), name='boards_list'),
    path('create/', CreateBoard.as_view(), name='create'),
    path('create/kanban', CreateKanban.as_view(), name='create_kanban'),
    path('<slug:board_slug>/tasks', BoardContentView.as_view(), name='board_content'),
]

src/tasksandboards/tasks/urls.py
from django.urls import path

from tasks.views import TasksList


app_name = 'tasks'

urlpatterns = [
    path('', TasksList.as_view(), name='tasks_list'),
]

src/tasksandboards/tasksandboards/urls.py
from core.views import StartPageView
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('boards/', include('boards.urls', namespace='boards')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('', StartPageView.as_view(), name='start_page'),

]

src/tasksandboards/boards/models/base.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy
from pytils.translit import slugify


class Board(models.Model):
    slug = models.SlugField(
        gettext_lazy('Слаг'),
        primary_key=True,
        unique=True,
        help_text=gettext_lazy('Только латинские буквы, цифры, `_`, `-`'),
    )
    name = models.CharField(
        gettext_lazy('Название'),
        max_length=settings.SHORT_LENGTH_CHARFIELD,
        unique=True,
        help_text=gettext_lazy('Только буквы и цифры'),
    )
    description = models.TextField(
        gettext_lazy('Описание'),
        max_length=settings.LONG_LENGTH_CHARFIELD,
        help_text=gettext_lazy('Только буквы, цифры и знаки припенания'),
        blank=True,
        default='',
    )
    owner = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        verbose_name=gettext_lazy('Владелец'),
        related_name='boards',
    )
    created = models.DateTimeField(
        gettext_lazy('Дата создания'),
        auto_now_add=True,
    )

    def __str__(self) -> str:
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    class Meta:
        abstract = True

src/tasksandboards/core/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class StartPageView(LoginRequiredMixin, TemplateView):
    template_name = 'core/start_page.html'


class SuccessView(TemplateView):
    """View for test success form."""

    template_name = 'core/success.html'

src/tasksandboards/templates/core/base.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
<!doctype html>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Многоформатный трекер для ведения заметок и проектов.">
        <link rel="stylesheet" href="{% static 'core/css/base.css' %}" />
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
        <script src="{% static 'core/js/htmx.js' %}" defer></script>
        {% block extrastyle %}{% endblock %}
        {% block title %}<title>Tasks&Boards</title>{% endblock %}
    </head>
    <body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
        {% if view_name  != 'accounts:login' %}
            {% include "includes/header.html" %}
        {% endif %}
        {% block content %}{% endblock %}
    </body>
</html>
{% endwith %}

src/tasksandboards/templates/core/start_page.html
{% extends "core/base.html" %}
{% load static %}
{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'core/css/start_page.css' %}" />
{% endblock %}
{% block content %}
    <main>
        <div class="content-layout">
            <a href="{% url "boards:create" %}" class="card">
                <h2>Создать доску</h2>
                <i class='bx bx-plus-circle' ></i>
            </a>
            <article class="card">
                <h2>Настройки</h2>
                <i class='bx bxs-cog'></i>
            </article>
            <article class="card">
                <h2>Справка</h2>
                <i class='bx bx-book-open'></i>
            </article>
            <article class="card">
                <h2>Поддержка</h2>
                <i class='bx bx-help-circle'></i>
            </article>
        </div>
    </main>
{% endblock %}

src/tasksandboards/templates/core/success.html
<!DOCTYPE html>
<html>
    <head>
        <style>
            .wrapper {
                display: flex;
                justify-content: center;
                align-items: center;
                width: 100%;
                height: 100vh;
            }
            .success_messege {
                width: 10rem;
                height: 5rem;
                border: 1px solid forestgreen;
                background: lightgreen;
                font-size: 3rem;
            }
        </style>
    </head>
    <div class="wrapper">
        <div class="success_messege">
            Действие выполненно успешно!
        </div>
    </div>
</html>