src/tasksandboards/boards/urls.py
from django.urls import path

from boards.views import BoardContentView, BoardsList, CreateBoard, CreateKanban


app_name = 'boards'

urlpatterns = [
    path('', BoardsList.as_view(), name='boards_list'),
    path('create/', CreateBoard.as_view(), name='create'),
    path('create/kanban', CreateKanban.as_view(), name='create_kanban'),
    path('<slug:board_slug>/tasks', BoardContentView.as_view(), name='board_content'),
]

src/tasksandboards/tasks/urls.py
from django.urls import path

from tasks.views import TasksList


app_name = 'tasks'

urlpatterns = [
    path('', TasksList.as_view(), name='tasks_list'),
]

src/tasksandboards/tasksandboards/urls.py
from core.views import StartPageView
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('boards/', include('boards.urls', namespace='boards')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('', StartPageView.as_view(), name='start_page'),

]

src/tasksandboards/boards/models/base.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy
from pytils.translit import slugify


class Board(models.Model):
    slug = models.SlugField(
        gettext_lazy('Слаг'),
        primary_key=True,
        unique=True,
        help_text=gettext_lazy('Только латинские буквы, цифры, `_`, `-`'),
    )
    name = models.CharField(
        gettext_lazy('Название'),
        max_length=settings.SHORT_LENGTH_CHARFIELD,
        unique=True,
        help_text=gettext_lazy('Только буквы и цифры'),
    )
    description = models.TextField(
        gettext_lazy('Описание'),
        max_length=settings.LONG_LENGTH_CHARFIELD,
        help_text=gettext_lazy('Только буквы, цифры и знаки припенания'),
        blank=True,
        default='',
    )
    owner = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        verbose_name=gettext_lazy('Владелец'),
        related_name='boards',
    )
    created = models.DateTimeField(
        gettext_lazy('Дата создания'),
        auto_now_add=True,
    )

    def __str__(self) -> str:
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    class Meta:
        abstract = True

src/tasksandboards/boards/models/kanban.py
from django.conf import settings
from django.db import models
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy

from boards.models.base import Board


class Kanban(Board):
    def get_absolute_url(self):
        return reverse_lazy('boards:board_content', kwargs={'board_slug': self.slug})


class Column(models.Model):
    name = models.CharField(
        gettext_lazy('Колонка'),
        max_length=settings.SHORT_LENGTH_CHARFIELD,
        help_text=gettext_lazy('Только буквы и цифры'),
    )
    position = models.SmallIntegerField()
    board = models.ForeignKey(
        Kanban,
        on_delete=models.CASCADE,
        verbose_name=gettext_lazy('Доска'),
        related_name='columns',
    )

    class Meta:
        ordering = ['position']

    def __str__(self) -> str:
        return self.name


# class Tasks(models.Model):
#     title = models.CharField(
#         gettext_lazy('Загаловок'),  # noqa: ERA001
#         max_length=settings.SHORT_LENGTH_CHARFIELD,  # noqa: ERA001
#         help_text=gettext_lazy('Только буквы, цифры и знаки припенания'),  # noqa: ERA001
#     )
#     description = models.TextField(
#         gettext_lazy('Описание'),  # noqa: ERA001
#         max_length=settings.LONG_LENGTH_CHARFIELD,  # noqa: ERA001
#         help_text=gettext_lazy('Только буквы, цифры и знаки припенания'),  # noqa: ERA001
#         blank=True,  # noqa: ERA001
#         null=True,  # noqa: ERA001
#     )
#     deadline = models.DateField(
#         gettext_lazy('Крайний срок'),  # noqa: ERA001
#     )
#     status = models.ForeignKey(
#         Column,
#         verbose_name=gettext_lazy('Статус'),  # noqa: ERA001
#         related_name='tasks',  # noqa: ERA001
#     )

src/tasksandboards/boards/forms.py
from django import forms
from django.utils.translation import gettext_lazy

from boards.models import Kanban
from boards.models.kanban import Column


class ColumnForm(forms.ModelForm):
    class Meta:
        model = Column
        fields = ['name', 'position']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'col-name', 'readonly': True}),
            'position': forms.TextInput(attrs={'class': 'col-pos', 'readonly': True}),
        }


ColumnFormset = forms.modelformset_factory(
    Column,
    form=ColumnForm,
    extra=0,
)


class CreateKanbanForm(forms.ModelForm):
    class Meta:
        model = Kanban
        fields = ['name', 'description']
        labels = {
            'name': gettext_lazy('Название'),
            'description': gettext_lazy('Описание'),
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-field-text'}),
            'description': forms.Textarea(
                attrs={
                    'class': 'form-field-textarea',
                    'rows': 6,
                    'cols': 27,
                    'wrap': 'soft',
                    'required': False,
                },
            ),
        }

src/tasksandboards/boards/views.py
from urllib import response
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.views.generic import CreateView, DetailView, ListView, TemplateView

from accounts.views import HtmxOnlyMixin
from boards.forms import ColumnFormset, CreateKanbanForm
from boards.models.kanban import Column, Kanban


class BoardsList(HtmxOnlyMixin, ListView):
    context_object_name = 'boards'
    template_name = 'boards/boards_list.html'

    def get_queryset(self):
        return Kanban.objects.filter(owner=self.request.user).values('slug', 'name')


class CreateBoard(LoginRequiredMixin, TemplateView):
    template_name = 'boards/create_board.html'


class CreateKanban(LoginRequiredMixin, CreateView):
    model = Kanban
    template_name = 'boards/create_kanban.html'
    form_class = CreateKanbanForm

    def get_context_data(self, **kwargs):
        if 'formset' not in kwargs:
            kwargs['formset'] = ColumnFormset(prefix='column', queryset=Column.objects.none())
        return super().get_context_data(**kwargs)

    def post(self, *args, **kwargs):
        self.object = None
        form = self.get_form()
        formset = ColumnFormset(prefix='column', data=self.request.POST, queryset=Column.objects.none())
        if form.is_valid() and formset.is_valid():
            return self.form_valid(form, formset)
        return self.form_invalid(form, formset)

    def form_valid(self, form, formset):
        board = form.save(commit=False)
        board.owner = self.request.user
        board.save()
        columns = formset.save(commit=False)
        if columns:
            for column in columns:
                column.board = board
                column.save()
        self.object = board
        return super().form_valid(form)

    def form_invalid(self, form, formset):
        return self.render_to_response(self.get_context_data(form=form, formset=formset))


class BoardContentView(LoginRequiredMixin, DetailView):
    template_name = 'boards/kanban_mockup.html'
    context_object_name = 'board'
    slug_url_kwarg = 'board_slug'

    def get_queryset(self):
        queryset = Kanban.objects.filter(owner=self.request.user)
        return queryset
    
    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        self.request.session['current_board'] = response.context_data.get('board').slug
        return response

src/tasksandboards/templates/boards/boards_list.html
{% for board in boards %}
    <li><a href="{% url "boards:board_content" board.slug %}">{{ board.name }}</a></li>
{% endfor %}

src/tasksandboards/templates/boards/create_board.html
{% extends "core/base.html" %}
{% load static %}
{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'boards/css/create_board.css' %}" />
{% endblock %}
{% block content %}
    <main>
        <div class="content-layout">
            <a hx-boost="false" href="{% url "boards:create_kanban" %}" class="card">
                <div class="card-info">
                    <p class="card-info-text">Канбан это система управления проектами основанная на колоночном макете.</p>
                    <span>!</span>
                </div>
                <h2>Канбан</h2>
                <i class="bx bx-plus-circle" ></i>
            </a>
        </div>
    </main>
{% endblock %}

src/tasksandboards/templates/boards/create_kanban.html
{% extends "core/base.html" %}
{% load static %}
{% block extrastyle %}<link href="{% static "boards/css/create_kanban.css" %}" rel="stylesheet"/>{% endblock %}
{% block content %}
    <main>
        <form action="{% url "boards:create_kanban" %}" method="post">
            {% csrf_token %}
            <h1>Создание доски</h1>
            {% if form.non_field_errors %}
                {{ form.non_field_errors }}
            {% endif %}
            {% for field in form %}
            <div class="input-wrapper">
                <label for={{ field.id_for_label }}>{{ field.label }}</label>
                {{ field }}
                <div class="row-breaker"></div>
                {% if field.errors %}
                    {{ field.errors }}
                {% endif %}
            </div>
            {% endfor %}
            <div class="input-wrapper">
                {{ formset.management_form }}
                <div class="cols-widget" data-cols-widget>
                    <label>Коллонки</label>
                    <div class="row-breaker"></div>
                    <input class="form-field-text" type="text" data-cols-widget-input>
                    <button type="button" class="btn" data-cols-widget-add-col-btn>Добавить</button>
                    <div class="row-breaker"></div>
                    <div class="cols-layout" data-cols-widget-output>
                        {% for form in formset %}
                            {% if form %}
                                <div class="col">
                                    {{ form.name }}
                                    {{ form.position }}
                                    <div class="col-order-btns-layout">
                                        <button type="button" class="btn" data-cols-widget-up-col-btn>▲</button>
                                        <button type="button" class="btn" data-cols-widget-down-col-btn>▼</button>
                                    </div>
                                    <button type="button" class="btn del-col-btn" data-cols-widget-del-col-btn>X</button>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <script src="{% static "boards/js/columns_widget.js" %}" defer></script>
                </div>
            </div>
            <div class="form-btn-layout">
                <button class="btn" type="submit">
                    <span>Сохранить</span>
                </button>
            </div>
        </form>
    </main>
{% endblock %}

src/tasksandboards/templates/boards/kanban_mockup.html
{% extends "core/base.html" %}
{% load static %}
{% block extrastyle %}<link href="{% static "boards/css/kanban_mockup.css" %}" rel="stylesheet"/>{% endblock %}
{% block content %}
<section class="calendar-switcher-layout">
    <menu>
        <li><a href="" class="calendar-switcher-btn-active btn"><span>Доска</span></a></li>
        <li><a href="" class="calendar-switcher-btn-notactive btn "><span>Календарь</span></a></li>
    </menu>
</section>
<main>
    {% for column in board.columns.all %}
        <section class="col-layout">
            <header class="col-header">
                <h2>{{ column.name }}</h2>
                <div class="dropdown-menu col-menu" data-col-menu>
                    <button class="col-menu-btn" data-col-menu-btn>
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-three-dots" viewBox="0 0 16 16">
                            <path d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3m5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3m5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3"/>
                        </svg>
                    </button>
                    <menu class="col-menu-items" data-col-menu-items>
                        <li><a>Пункт меню</a></li>
                        <li><a>Пункт меню</a></li>
                    </menu>
                </div>
            </header>
            <div class="task-card-layout">
                <span hx-get="{% url "tasks:tasks_list" %}?status={{column.pk}}"
                      hx-swap="outerHTML"
                      hx-trigger="load"
                      hx-target="this"
                >
                </span>
            </div>
        </section>
    {% endfor %}
</main>
{% endblock %}