src/tasksandboards/accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from accounts.views import ConfirmSignupView, LoginView, SigninView, SignupView


app_name = 'accounts'

urlpatterns = [
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('signin', SigninView.as_view(), name='signin'),
    path('signup', SignupView.as_view(), name='signup'),
    path('confirm_signup', ConfirmSignupView.as_view(), name='confirm_signup'),
]

src/tasksandboards/boards/urls.py
from django.urls import path

from boards.views import BoardContentView, BoardsList, CreateBoard, CreateKanban


app_name = 'boards'

urlpatterns = [
    path('', BoardsList.as_view(), name='boards_list'),
    path('create/', CreateBoard.as_view(), name='create'),
    path('create/kanban', CreateKanban.as_view(), name='create_kanban'),
    path('<slug:board_slug>/tasks', BoardContentView.as_view(), name='board_content'),
]

src/tasksandboards/tasks/urls.py
from django.urls import path

from tasks.views import TasksList


app_name = 'tasks'

urlpatterns = [
    path('', TasksList.as_view(), name='tasks_list'),
]

src/tasksandboards/tasksandboards/urls.py
from core.views import StartPageView
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('boards/', include('boards.urls', namespace='boards')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('', StartPageView.as_view(), name='start_page'),

]

src/tasksandboards/templates/includes/header.html
<header class="main-header ">
    <nav>
        <input type="checkbox" name="menu-switch" id="menu-switch" />
        <label for="menu-switch" class="menu-btn">
            <i class='bx bx-sidebar'></i>
        </label>
        <label for="menu-switch" class="menu-btn-cls">
            <i class='bx bx-x'></i>
        </label>
        <aside>
            <menu class="main-nav-menu">
                <span hx-get="{% url 'boards:boards_list' %}" hx-trigger="revealed" hx-target="this" hx-swap="outerHTML"></span>
            </menu>
            <div class="add-btn-layout">
                <button class="btn add-btn">
                    <i class='bx bx-plus-circle' ></i>
                </button>
            </div>
        </aside>
    </nav>
    <section class="account-layout">
      <a class="lnk" href="">{{ user }}</a>
      <a class="lnk" hx-boost="false" href="{% url 'accounts:logout' %}">Выход</a>
    </section>
</header>